# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2368ca356ee5c29d91ff571524eb4c951fc185ebd50dad82d2fdc9edb3abcb2513e53bfa362e490cb154acf3532992d41d94bd1f632fc62b3200a6da083f79af

test:
  secret_key_base: d978f988a9df639bc7bdd9c2899c9c95604b1145742bb8c4e3cd493f4a6f5e1ab9ded84d81d894f71f0ed5c3652c93452468526ac6c5926242c34b5b73667ddb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
